### ISSUE TITLE
Error check: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by ChristineLin00** [omadson/fuzzy-c-means#23]
I try the code below:
```python
	from sklearn import datasets
	X, y = datasets.load_iris(return_X_y=True)
	mod = FCM(n_clusters=14, max_iter=150, m=2)
	mod.fit(X.T)
```
and then got this error: array must not contain infs or NaNs

I think maybe the parameter `u` has the nan and then `norm(u - u2)` wouldn't be calculated.
Hence, I have the suggestion that you can add the below code before `norm(u - u2)`
```python
	if True in pd.isnull(u):
		u = u2
		break
```
Thanks.

**Comment by omadson** [comment]
Yeah, I have to deal with that kind of bug. However, in your example, you should use `mod.fit(X)` instead of `mod.fit(X.T)`.

**Comment by ChristineLin00** [comment]
Thanks for your replay and correct. The purpose of the example  `mod.fit(X.T)`  is  wanting to  show some issue simply.

**Comment by omadson** [comment]
Guy. Sorry my late. 

What version are you using? I tested the example you presented and in my environment it ran normally.

**Comment by omadson** [comment]
I'm closing this issue.
