### ISSUE TITLE
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.

### ISSUE THREAD

**Issue by cassoulettia** [omadson/fuzzy-c-means#30]
I am on Linux on a virtual machine, and i really don't understand this error, or what I have to do. 
Thank you in advance.

**Comment by omadson** [comment]
Hello @cassoulettia. I'll try to change to numba lib as the main dependency. Using numba we won't have problems with different versions for windows and linux.

**Comment by jtremesay-sereema** [comment]
@cassoulettia a short explanation of the issue, 

As you may know, a processor execute [instructions](https://en.wikipedia.org/wiki/Instruction_set_architecture). Their are many instructions: for getting a value from the memory, adding two numbers, storing a value to the memory… In 2008, Intel introduced the [AVX instructions](https://en.wikipedia.org/wiki/Instruction_set_architecture), a set of instructions for doing operations on multiple values in parallel. These instructions can speed up math-heavy programs, so jaxlib was compiled to use them. Unfortunately, it look like your processor doesn’t support these instructions (`This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support`).  The recommendation in the error message (`You may be able work around this issue by building jaxlib from source`) is to build the jaxlib yourself so it will be compatible with your processor.

hope I helped you understand the error
