### ISSUE TITLE
fuzzy-c-means 1.4.0 break the logging system

### ISSUE THREAD

**Issue by jtremesay-sereema** [omadson/fuzzy-c-means#32]
Hi,

Not exactly true, but the 1.4.0 break all our debug, info and warning logs. I think that the culprit is this [line](https://github.com/omadson/fuzzy-c-means/blob/master/fcmeans/_jax.py#L5). Is it possible to do something about it?

Best regards,
Jo

**Comment by omadson** [comment]
Hello, @jtremesay-sereema I guess this issue is solved by #40. Can you check?

**Comment by jtremesay-sereema** [comment]
our logs are back with the latest version. Thx!
