### ISSUE TITLE
Question about the parameters

### ISSUE THREAD

**Issue by maxiannunziata** [omadson/fuzzy-c-means#4]
in the parameters:

m: represent exponent for the fuzzy partition matrix.
What represent 30% ? m=1.3 or m=30 ?

Thanks!

**Comment by omadson** [comment]
Hi, guy, thanks for your interest in the library.

Well, the parameter `m` doesn't work like that. This parameter corresponds to the degree of "fuzziness" of the solution. Large values of `m` will make all elements belong to all clusters. While small values will make the solution look more like the _K_-means soluction.

For a more in-depth explanation about the parameter `m`, I suggest reading the following article:
 - [On the selection of m for Fuzzy c-Means](https://download.atlantis-press.com/article/23735.pdf)

**Comment by maxiannunziata** [comment]
Thank you @omadson
