### ISSUE TITLE
The examples directory listed at pypi.org does not exist

### ISSUE THREAD

**Issue by raymondj-pace** [omadson/fuzzy-c-means#54]
Go to here:
https://pypi.org/project/fuzzy-c-means/

Scroll-down to where it says: 

to more examples, see the [examples/](https://github.com/omadson/fuzzy-c-means/tree/master/examples) folder.

https://github.com/omadson/fuzzy-c-means/tree/master/examples leads to a 404

**Comment by omadson** [comment]
Thanks, @raymondj-pace. I will fix the broken link in an upcoming update. The correct link is: https://github.com/omadson/fuzzy-c-means/tree/master/docs/examples

**Comment by omadson** [comment]
I'm closing the issue due to lack of activity. It can be reopened at any time.
