### ISSUE TITLE
hello, how do i use this method the fuzz-c-means, what the parameters of this .py?

### ISSUE THREAD

**Issue by Sher-Liu** [omadson/fuzzy-c-means#60]
I didn't find the .py file.

**Comment by omadson** [comment]
Hello @Sher-Liu. Can you provide more information about this question?

You can use general GitHub etiquette.

- Write in complete sentences and avoid writing run-on sentences. Grammatical mistakes for non-native speakers of English  are of course understandable, so long as an honest effort made.
- More importantly, when requesting help, it is expected that users provide example code, example outputs, and a description of expected output. When relevant, it can be helpful to specify system information and pertinent package versions.

**Comment by omadson** [comment]
I'm closing the issue due to lack of activity. It can be reopened at any time.
