### ISSUE TITLE
Support for custom distance metrics

### ISSUE THREAD

**Issue by meghbhalerao** [omadson/fuzzy-c-means#61]
Hello,
I could not find it, but is there support for custom distance metrics such a cosine similarity which is widely used in clustering in this package? Or does the FCM algorithm just use the euclidean squared distance metric?
Thanks and please let me know.

**Comment by omadson** [comment]
Hi @meghbhalerao.

I've just added support for custom functions, as well as some standard options (cosine and Minkowski).

To use the new features, update the library to version `1.7.0`.

Hope you can use it.
