### ISSUE TITLE
Error when using more than 100 clusters

### ISSUE THREAD

**Issue by shahvaiz** [omadson/fuzzy-c-means#76]
Hello,

I am trying to perform clustering with 300 clusters but I am getting an error. Is it possible to increase the maximum number of clusters?

Thank you,
Shahvaiz Hanif

<img width="1006" alt="FCM error" src="https://github.com/omadson/fuzzy-c-means/assets/2415313/4c4b21ac-5591-4227-af6e-2a5967c42bd8">

**Comment by omadson** [comment]
Hi @shahvaiz. Thank you for being interested in the `fuzzy-c-means` library.

To modify the maximum limit on the number of clusters, you can define it after creating the `fcm` object.

Try to use the following snippet before model fit:

```Python
fcm = FCM()
fcm.n_clusters = 300
```

I hope it helps you.

---

**Note**: Be careful when using Fuzzy C-means algorithm in high dimensions. In these cases, the distances become very similar, which compromises the fit of the model.  For more details check [this paper](https://dl.acm.org/doi/abs/10.4018/ijfsa.2011010101).

**Comment by omadson** [comment]
I'm closing the issue due to lack of activity. It can be reopened at any time.
