### ISSUE TITLE
Update pydantic >2 version

### ISSUE THREAD

**Issue by Martin-Molinero** [omadson/fuzzy-c-means#86]
- fuzzy-c-means 1.7.0 depends on pydantic<2.0.0 and >=1.9.0, would be nice to support > 2

**Comment by Martin-Molinero** [comment]
Thank you @omadson! Could the pypip version be updated?

**Comment by omadson** [comment]
Hi @Martin-Molinero. You got it! https://pypi.org/project/fuzzy-c-means/
